import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Sidbar from "./components/sidbar";
import Footer from "./components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="min-h-screen flex flex-col">
        <div><Header/></div>
        <div className="flex-grow grid grid-cols-[200px_minmax(400px,_1fr)_100px] ">
          <div className=" "><Sidbar/></div>
          <div className="">{children}</div>
        </div>
        <div className=" relative bottom-0 block bg-white p-3 text-center"><Footer/></div>
      </div>
      </body>
    </html>
  );
}
